# Generated by Django 2.1.5 on 2022-11-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assistance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistance_info',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
