# Generated by Django 2.1.5 on 2022-11-12 00:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assistance', '0003_auto_20221111_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistance_info',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 12, 0, 34, 25, 479593)),
        ),
    ]
