# Generated by Django 2.1.5 on 2022-11-14 01:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assistance', '0016_alter_assistance_info_create_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistance_info',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 14, 1, 30, 39, 972064)),
        ),
        migrations.AlterField(
            model_name='assistance_info',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
