# Generated by Django 4.1.1 on 2022-10-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items_info',
            name='offer_status',
            field=models.BooleanField(default=True),
        ),
    ]
