# Generated by Django 4.1.1 on 2022-10-15 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0003_alter_items_info_offer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items_info',
            name='offer_status',
        ),
    ]
