# Generated by Django 4.1.1 on 2022-10-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0006_alter_items_info_offer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='items_info',
            name='image',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='items_info',
            name='name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
