# Generated by Django 4.1.1 on 2022-10-29 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0008_rename_image_items_info_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items_info',
            old_name='url',
            new_name='image',
        ),
    ]
