# Generated by Django 4.1.1 on 2022-10-29 14:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0019_alter_items_info_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='items_info',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='items_info',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
