# Generated by Django 4.1.3 on 2022-11-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0020_items_info_create_time_items_info_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items_info',
            name='image',
            field=models.ImageField(max_length=1000, upload_to='product/'),
        ),
    ]
