# Generated by Django 2.1.5 on 2022-11-14 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0023_alter_items_category_id_alter_items_info_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items_category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='items_info',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
