# Generated by Django 4.1.1 on 2022-10-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_info',
            name='total_price',
        ),
        migrations.AddField(
            model_name='order_total',
            name='total_price',
            field=models.FloatField(default=0),
        ),
    ]
