# Generated by Django 4.1.1 on 2022-11-02 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_remove_order_info_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_total',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
