# Generated by Django 4.1.2 on 2022-11-12 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_order_total_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_info',
            name='payment_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order_total',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]