# Generated by Django 4.1.3 on 2022-11-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_auto_20221110_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_info',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='order_info',
            name='payment_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order_total',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='order_total',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
