# Generated by Django 4.1.1 on 2022-11-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_info',
            name='customer_id',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
