# Generated by Django 4.1.3 on 2022-11-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_booking_info_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_info',
            name='book_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking_info',
            name='book_time',
            field=models.CharField(max_length=100),
        ),
    ]
