# Generated by Django 2.1.5 on 2022-11-12 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0005_booking_info_book_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_info',
            name='book_name',
        ),
        migrations.RemoveField(
            model_name='booking_info',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='booking_info',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
