# Generated by Django 2.1.5 on 2022-11-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0006_auto_20221112_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_info',
            name='book_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking_info',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
    ]
