# Generated by Django 2.1.5 on 2022-11-14 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0008_alter_booking_info_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_info',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
